name: E2E on Chrome
on: [push, pull_request]
jobs:
  cypress-run:
    name: Cypress

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm install

      - run: pnpm build

      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
